Add functionaly for SMIRNOFF convention of permuting atoms for improper calculations
choderalab/espaloma pull request #105
Opened 2022-02-14 19:43 UTC by kaminow

Added functionality to use SMIRNOFF convention for impropers instead of the current espaloma convention. Current default options will use the SMIRNOFF convention for newly created molecules. When datasets are loaded, no changes will be made if using the default options, however if an argument for `improper_def` is provided, the `n4_improper` nodes will be regenerated according to the provided input.

Resolves #101.

2022-02-17 17:23 UTC, yuanqing-wang requested changes
thanks for this PR! I think this would do exactly what we wanted to do!

only comment is that it would be nice if we can move the heavy lifting to a utility script and keep the `esp.Graph` unchanged

2022-02-17 17:23 UTC, yuanqing-wang commented on espaloma/graphs/graph.py
> +    def __init__(self, mol=None, homograph=None, heterograph=None,
this modification is a bit too aggressive as we need to supply another arguments at the very beginning stage of graph definition. can we not touch the `esp.graph` part and move this to another utility function where we take a `esp.Graph` and modify in-place?

2022-02-17 17:23 UTC, yuanqing-wang commented on espaloma/data/dataset.py
> +    def load(cls, path, improper_def=None):
same as in `esp.graph`. looks like this is changing too much of the mainline code

2022-02-17 17:23 UTC, yuanqing-wang commented on espaloma/nn/readout/janossy.py
> +        if improper_def not in ('smirnoff', 'espaloma'):
might be nice moving this to another object called `JanossyPoolingWithSmirnoffImproper` or whatever

2022-02-17 19:26 UTC, jchodera commented
> only comment is that it would be nice if we can move the heavy lifting to a utility script and keep the esp.Graph unchanged

Which "heavy lifting" are you referring to specifically, @yuanqing-wang ? Do you just mean the Janossy pooling variant schemes should be moved to objects/classes?

2022-02-17 19:37 UTC, yuanqing-wang commented
> > only comment is that it would be nice if we can move the heavy lifting to a utility script and keep the esp.Graph unchanged
> 
> Which "heavy lifting" are you referring to specifically, @yuanqing-wang ? Do you just mean the Janossy pooling variant schemes should be moved to objects/classes?

at this stage, I think the enumeration of the improper indices should be moved to a utility function as opposed to handled in the `esp.Graph` object

2022-02-18 18:45 UTC, yuanqing-wang commented
It would be great to move it to graph.utils

> On Feb 18, 2022, at 1:09 PM, kaminow ***@***.***> wrote:
> 
> 
> @kaminow commented on this pull request.
> 
> In espaloma/graphs/graph.py <https://github.com/choderalab/espaloma/pull/105#discussion_r810233273>:
> 
> > @@ -44,7 +44,8 @@ class Graph(BaseGraph):
>  
>      """
>  
> -    def __init__(self, mol=None, homograph=None, heterograph=None):
> +    def __init__(self, mol=None, homograph=None, heterograph=None,
> does it make sense to keep the regenerate_impropers method as a member of the esp.Graph class or should I move it to graph.utils?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/choderalab/espaloma/pull/105#discussion_r810233273>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGLMHA47YARB2IE7QXASQXDU32DMTANCNFSM5OMM4ISQ>.
> You are receiving this because you were mentioned.
>

2022-02-18 21:14 UTC, yuanqing-wang approved these changes

2022-02-18 21:17 UTC, merged